Translated Conditional Rendering article
reactjs/pl.reactjs.org pull request #302
Opened 2021-12-21 12:45 UTC by lukbar48

2021-12-25 16:02 UTC, jakubdrozdek requested changes
Hej, dzięki, dobra robota. Z racji tego, że to Twój pierwszy PR, to nieuniknione, że będzie parę rzeczy do poprawy. Nie łam się 👍🏻 Popraw proszę tłumaczenie i możesz zabierać się do kolejnych artykułów :-)

2021-12-25 16:02 UTC, jakubdrozdek commented on beta/src/pages/learn/conditional-rendering.md
> +  herbata: {
Mimo wszystko, ja bym nie tłumaczył nazw zmiennych/kluczy, mimo że JS to łyknie. Niech kod będzie angielski, a **wyświetlane** teksty polskie. Jeśli to konieczne, dodałbym kolejne warunki renderujące tekst, jak w komentarzu wyżej.

2022-01-01 22:16 UTC, jakubdrozdek commented
@lukbar48 Nadal masz kilka nierozwiązanych wątków w tym PR-ze. Popraw proszę.

2022-01-05 16:26 UTC, lukbar48 commented
> @lukbar48 Nadal masz kilka nierozwiązanych wątków w tym PR-ze. Popraw proszę.

Nie jestem pewien czy wszystko zostało rozwiązane, jeśli nie daj znać.

2022-01-10 22:26 UTC, jakubdrozdek commented
@lukbar48 Chodzi o to, że kliknąłeś "resolve", ale nie poprawiłeś samego tłumaczenia ;) Nie tłumaczymy nazw zmiennych na polski - zostawiamy oryginalne, angielskie. W kodzie na końcu pliku masz `<dd>{info.część}</dd>` itp.
Cofnąłem "resolve" na nich - powinny się pojawić jako nierozwiązane wątki.

2022-01-12 21:49 UTC, jakubdrozdek approved these changes

2022-01-12 21:58 UTC, merged