[WIP] Rendering Lists
reactjs/pl.reactjs.org pull request #339
Opened 2022-05-23 18:26 UTC by cyntler

2023-07-04 09:44 UTC, LukaszGrela requested changes

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +Fragmenty znikają z DOM, więc powyższy kod wygeneruje płaską listę `<h1>`, `<p>`, `<h1>`, `<p>` i tak dalej.
Nic nie znika:) bo nigdy w DOMie nie były
```suggestion
Fragmenty nie są dodawane jako elementy DOM, więc powyższy kod wygeneruje płaską listę `<h1>`, `<p>`, `<h1>`, `<p>` i tak dalej.
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +Co robić, gdy każdy element musi renderować nie jeden, ale kilka węzłów DOM?
```suggestion
Co zrobić, gdy każdy element musi renderować nie jeden, ale kilka węzłów DOM?
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +Krótka składnia fragmentów `<></>` nie pozwoli Ci przekazać klucza, więc musisz albo zgrupować je w pojedynczy `<div>`, albo użyć nieco dłuższej i bardziej wyraźnej składni `<Fragment>`:
Angielska wersja jest nielogiczna, zeby nie powiedziec bledna, zadaje pytanie by potem nie udzielic odpowiedzi. Nalezaloby napisac

```suggestion
Możemy "opakować" te elementy w pojedynczy element np. `<div>` który stanie się częścią zwróconego drzewa DOM. Jednak w przypadku gdy takie zachowanie nie jest porządane React udostępnia specjalny komponent stworzony dla tego celu: [`<Fragment>`](https://react.dev/reference/react/Fragment):
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +### Skąd wziąć `key` {/*where-to-get-your-key*/}
```suggestion
### Skąd wziąć atrybut `key` {/*where-to-get-your-key*/}
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +* **Dane z bazy danych:** Jeśli Twoje dane pochodzą z bazy danych, możezz użyć kluczy/identyfikatorów podchodzących z tabel baz danych, które z natury są unikatowe.
```suggestion
* **Dane z bazy danych:** Jeśli Twoje dane pochodzą z bazy danych, możesz użyć kluczy/identyfikatorów podchodzących z tabel baz danych, które z założenia są unikatowe.
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +* **Dane generowane lokalnie:** Jeśli Twoje dane są generowane i przechowywane lokalnie (np. notatki w aplikacji notatnika), możesz użyć inkrementowanego licznika, [`crypto.randomUUID()`](https://dev
```suggestion
* **Dane generowane lokalnie:** Jeśli Twoje dane są generowane i przechowywane lokalnie (np. notatki w aplikacji notatnika), możesz użyć inkrementowanego licznika, metody [`crypto.randomUUID()`](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID) lub modułu jak [`uuid`](https://www.npmjs.com/package/uuid) do wygenerowania unikalnego identyfikatora podczas tworzenia elementów.
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +### Reguły kluczy {/*rules-of-keys*/}
```suggestion
### Reguły tworzenia kluczy {/*rules-of-keys*/}
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +Zauważ, że twoje komponenty nie otrzymają `key` jako property komponentu. Jest on używany tylko jako wskazówka przez sam React. Jeśli twój komponent potrzebuje identyfikatora, musisz przekazać go jak
```suggestion
Zauważ, że twoje komponenty nie otrzymają `key` jako atrybutu komponentu. Jest on używany tylko jako wskazówka przez sam React. Jeśli twój komponent potrzebuje identyfikatora, musisz przekazać go jako osobny atrybut. Przykład: `<Profile key={id} userId={id} />`.
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +* Jak przenieść dane do struktur danych, takich jak tablice i obiekty.
```suggestion
* Jak przenieść dane do struktur danych takich jak tablice i obiekty.
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +* Dlaczego i jak ustawić `key` na każdym komponencie w kolekcji, aby React mógł śledzić każdy z nich, nawet jeśli zmieni się ich pozycja lub dane.
```suggestion
* Dlaczego i jak ustawić atrybut `key` na każdym komponencie w kolekcji, aby React mógł śledzić każdy z nich, nawet jeśli zmieni się ich pozycja lub dane.
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +Ten przykład ukazuje listę wszystkich ludzi.
Raczej nie wszystkich ludzi:)

```suggestion
Ten przykład pokazuje listę profesjonalistów.
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +Zmieńmy go, aby pokazać dwie osobne listy, jedna pod drugą: **Chemicy** oraz **Wszyscy inni**. Podobnie jak poprzednio, możesz określić, która osoba jest chemikiem, sprawdzając czy `person.profession
```suggestion
Zmień go tak, aby pokazać dwie osobne listy, jedna pod drugą: **Chemicy** oraz **Pozostali**. Podobnie jak poprzednio, możesz określić, która osoba jest chemikiem, sprawdzając warunek `person.profession === 'chemist'`.
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +Bardzo uważna osoba może zauważyć, że przy dwóch wywołaniach `filter` sprawdzamy zawód każdej osoby dwa razy. Sprawdzenie właściwości jest bardzo szybkie, więc w tym przykładzie jest w porządku. Jeśl
```suggestion
Bardzo uważna osoba może zauważyć, że przy dwóch wywołaniach `filter` sprawdzamy zawód każdej osoby dwa razy. Sprawdzenie właściwości jest bardzo szybkie, więc w tym przykładzie jest to w porządku. Jeśli twoja logika byłaby bardziej skomplikowana, mógłbyś zastąpić wywołania `filter` pętlą która przejdzie przez tablicę i sprawdzi każdą osobę tylko jeden raz.
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +W rzeczywistości, jeśli `people` nigdy się nie zmienią, mógłbyś przenieść ten kod na zewnątrz swojego komponentu. Z perspektywy Reacta, jedyne, co ma znaczenie, to końcowa tablica węzłów JSX. Nie obc
```suggestion
Właściwie, jeśli tablica `people` nigdy się nie zmienia, mógłbyś przenieść ten kod na zewnątrz swojego komponentu. Z perspektywy Reacta, jedyne, co ma znaczenie, to końcowa tablica węzłów JSX. Nie obchodzi go, jak utworzysz tę tablicę:
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +Zrób listę przepisów z tej tablicy! Dla każdego przepisu w tablicy wyświetl jego tytuł jako `<h2>` i wymień jego składniki za pomocą `<ul>`.
```suggestion
Zrób listę przepisów z tej tablicy! Dla każdego przepisu wyświetl jego tytuł jako `<h2>` i wymień jego składniki za pomocą `<ul>`.
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +Będzie to wymagało zagnieżdżenia dwóch różnych wywołań `map`.
```suggestion
Będzie to wymagało zagnieżdżenia dwóch różnych wywołań metody `map`.
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +Każdy element z `recipes` (przepisów) zawiera już pole `id`, więc tego używa zewnętrzna pętla dla swojego klucza `key`. Nie ma identyfikatora, którego można by użyć do zapętlenia składników. Rozsądne
```suggestion
Każdy element z tablicy `recipes` (przepisów) zawiera już pole `id`, więc tego używa zewnętrzna pętla dla swojego atrybutu `key`. Nie ma identyfikatora, którego można by użyć do zapętlenia składników. Rozsądne jest jednak założenie, że ten sam składnik nie zostanie wymieniony dwa razy w ramach tego samego przepisu, więc jego nazwa może służyć jako `key`. Alternatywnie możesz zmienić strukturę danych, aby dodać identyfikatory, lub użyć indeksu jako `key` (z zastrzeżeniem, że nie możesz bezpiecznie zmienić kolejności składników).
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +### Wyodrębnianie elementu listy {/*extracting-a-list-item-component*/}
```suggestion
### Wyodrębnianie komponentu "element listy" {/*extracting-a-list-item-component*/}
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +Ten komponent `RecipeList` zawiera dwa zagnieżdżone wywołania `map`. Aby to uprościć, wyodrębnij z niego komponent `Recipe`, który akceptuje właściwości `id`, `name` i `ingredients`. Gdzie umieścisz
```suggestion
Komponent `RecipeList` zawiera dwa zagnieżdżone wywołania `map`. Aby to uprościć, wyodrębnij z niego komponent `Recipe`, który akceptuje atrybuty `id`, `name` i `ingredients`. Gdzie umieścisz zewnętrzny atrybut `key` i dlaczego?
```

2023-07-04 09:44 UTC, LukaszGrela commented on beta/src/pages/learn/rendering-lists.md
> +Możesz skopiować i wkleić JSX z zewnętrznego wykonania `map` do nowego komponentu `Recipe` i zwrócić ten JSX. Następnie możesz zmienić `recipe.name` na `name`, `recipe.id` to `id` itd. i przekazać je
```suggestion
Możesz skopiować i wkleić JSX z zewnętrznego wykonania `map` do nowego komponentu `Recipe` i zwrócić ten JSX. Następnie możesz zmienić `recipe.name` na `name`, `recipe.id` na `id` itd. i przekazać je jako atrybuty (props) do `Recipe`:
```

2025-06-19 13:51 UTC, dawidsabat commented
Page already translated in #460. Closing.

2025-06-19 13:51 UTC, closed without merging