Start a new react project
reactjs/pl.reactjs.org pull request #444
Opened 2023-12-26 20:52 UTC by dawidowski

2023-12-26 20:57 UTC, dawidowski commented
Już podczas tłumaczenia zauważyłem, że temat nie jest dla mnie tak prosty jak mi się wydawało i zdaje sobie sprawę, że może być tu sporo błędów. Mimo to, postarałem się jak mogłem i dokończyłem już zaczętą pracę. Proszę o wyrozumiałość, jednocześnie proszę się nie hamować i zwracać uwagę na każdy, nawet najmniejszy błąd 😄

2024-02-26 00:08 UTC, jakubdrozdek requested changes

2024-02-26 00:08 UTC, jakubdrozdek commented on src/content/learn/start-a-new-react-project.md
> +Gatsby jest utrzymywane przez [Netlify](https://www.netlify.com/). Możesz [wdrożyć w pełni statyczną stronę Gatsby](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting) na dowolnym hostingu
```suggestion
Gatsby jest utrzymywane przez [Netlify](https://www.netlify.com/). Możesz [wdrożyć w pełni statyczną stronę stworzoną w Gatsbym](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting) na dowolnym hostingu statycznym. Jeśli zdecydujesz się na korzystanie z funkcji obsługiwanych tylko przez serwer, upewnij się, że twój dostawca hostingu wspiera je dla Gatsby'ego.
```

2024-02-26 00:08 UTC, jakubdrozdek commented on src/content/learn/start-a-new-react-project.md
> +**[Expo](https://expo.dev/) to framework reactowy, który pozwala tworzyć uniwersalne aplikacje na Androida, iOS oraz webowe z prawdziwie natywnym interfejsem użytkownika.** Dostarcza on SDK dla [Reac
```suggestion
**[Expo](https://expo.dev/) to framework reactowy, który pozwala tworzyć uniwersalne aplikacje na Androida, iOS oraz webowe z prawdziwie natywnym interfejsem użytkownika.** Dostarcza on SDK dla [React Native](https://reactnative.dev/), które ułatwia korzystanie z natywnych funkcjonalności. Aby utworzyć nowy projekt z Expo, uruchom komendę:
```

2024-02-26 00:08 UTC, jakubdrozdek commented on src/content/learn/start-a-new-react-project.md
> +Jeśli Expo jest dla siebie nowy, zajrzyj do jego [samouczka](https://docs.expo.dev/tutorial/introduction/).
```suggestion
Jeśli Expo jest dla ciebie nowy, zajrzyj do jego [samouczka](https://docs.expo.dev/tutorial/introduction/).
```

2024-02-26 00:08 UTC, jakubdrozdek commented on src/content/learn/start-a-new-react-project.md
> +Nawet jeśli początkowo nie potrzebujesz nawigacji ani pobierania danych, prawdopodobnie później będziesz chcieć dodać pewne biblioteki do ich obsługi. W miarę jak twój bundle rośnie z każdą nową funk
```suggestion
Nawet jeśli początkowo nie potrzebujesz nawigacji ani pobierania danych, prawdopodobnie później będziesz chcieć dodać pewne biblioteki do ich obsługi. W miarę jak twoja paczka kodu rośnie z każdą nową funkcją, możesz musieć zastanowić się, jak podzielić kod dla każdego widoku z osobna. Gdy potrzeby dotyczące pobierania danych stają się bardziej złożone, prawdopodobnie napotkasz problemy związane z kaskadami żądań sieciowych między serwerem a klientem, które sprawiają, że twoja strona będzie działała bardzo wolno. Gdy aplikacja zaczyna obsługiwać więcej użytkowników z kiepskim połączeniem sieciowym i urządzeniami niskiej jakości, możesz potrzebować generować HTML z twoich komponentów, aby wyświetlać zawartość wcześniej - albo na serwerze, albo podczas budowania. Zmiana w celu uruchamiania części kodu na serwerze lub podczas budowania może być bardzo trudna.
```

2024-02-26 00:08 UTC, jakubdrozdek commented on src/content/learn/start-a-new-react-project.md
> +**Wymienione tu frameworki Reacta, rozwiązują te problemy, bez dodatkowej pracy z twojej strony.** Pozwalają rozpocząć od bardzo podstawowej konfiguracji, a następnie rozwijać aplikację zgodnie z two
```suggestion
**Wymienione tu frameworki reactowe rozwiązują te problemy bez dodatkowej pracy z twojej strony.** Pozwalają rozpocząć od bardzo podstawowej konfiguracji, a następnie rozwijać aplikację zgodnie z twoimi potrzebami. Każdy framework dla Reacta ma swoją społeczność, co ułatwia znalezienie odpowiedzi na pytania i aktualizację narzędzi. Frameworki te również nadają strukturę twojemu kodowi, pomagając tobie i innym zachować kontekst i umiejętności pomiędzy różnymi projektami. Inaczej, korzystając z niestandardowego rozwiązania, łatwiej jest utknąć na niewspieranych wersjach zależności i w zasadzie skończyć tworząc swój własny framework, bez społeczności i sposobów ulepszeń (i jeśli będzie on w jakiś sposób podobny do tych, które stworzyliśmy wcześniej, będzie on bardziej chaotycznie zaprojektowany).
```

2024-02-26 00:08 UTC, jakubdrozdek commented on src/content/learn/start-a-new-react-project.md
> +Komponenty serwerowe i Suspense są funkcjonalnościami Reacta, a nie samego Next.js. Jednakże, ich zaadaptowanie w frameworku wymaga akceptacji i znacznej pracy. W chwili obecnej, App Router z Next.js
```suggestion
Komponenty serwerowe i Suspense są funkcjonalnościami Reacta, a nie samego Next.js. Jednakże ich zaadaptowanie w frameworku wymaga akceptacji i znacznej pracy. W chwili obecnej, App Router z Next.js jest ich najpełniejszą implementacją. Zespół Reacta współpracuje z deweloperami bundlerów, aby ułatwić implementację tych funkcjonalności w frameworkach następnej generacji.
```

2024-03-28 19:55 UTC, jakubdrozdek approved these changes

2024-03-28 19:56 UTC, merged