Rendering lists
reactjs/pl.reactjs.org pull request #445
Opened 2024-01-07 21:32 UTC by dawidowski

2024-02-26 00:33 UTC, jakubdrozdek requested changes

2024-02-26 00:33 UTC, jakubdrozdek commented on src/content/learn/rendering-lists.md
> +Często będziesz potrzebować wyświetlać wiele podobnych komponentów na podstawie kolekcji danych. Możesz użyć [javascriptowych metod tablic](https://developer.mozilla.org/docs/Web/JavaScript/Reference
```suggestion
Często zdarzy ci się wyświetlać wiele podobnych komponentów na podstawie kolekcji danych. Możesz użyć [javascriptowych metod tablicowych](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array#), aby manipulować tablicą danych. Będziesz tu korzystać z [`filter()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) i [`map()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array/map) w połączeniu z Reactem, aby przefiltrować i przekształcić tablicę danych w tablicę komponentów.
```

2024-02-26 00:33 UTC, jakubdrozdek commented on src/content/learn/rendering-lists.md
> +Jedyna różnica między elementami tej listy to ich treść, ich dane. Często będziesz chcieć pokazać kilka instancji tego samego komponentu, używając różnych danych podczas tworzenia interfejsów: od lis
```suggestion
Jedyna różnica między elementami tej listy to ich treść, ich dane. Często będziesz chcieć pokazać kilka instancji tego samego komponentu, używając różnych danych podczas tworzenia interfejsów: od list komentarzy do galerii obrazków profilowych. W takich sytuacjach możesz przechowywać te dane w obiektach i tablicach javascriptowych oraz używać metod, takich jak [`map()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) i [`filter()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array/filter), aby renderować na ich podstawie listy komponentów.
```

2024-02-26 00:33 UTC, jakubdrozdek commented on src/content/learn/rendering-lists.md
> +Później na tej stronie, dowiesz się jak naprawić ten błąd. Zanim do tego przejdziemy, nadajmy trochę struktury twoim danym.
```suggestion
Poniżej na tej stronie dowiesz się, jak naprawić ten błąd. Zanim do tego przejdziemy, nadajmy trochę struktury twoim danym.
```

2024-02-26 00:33 UTC, jakubdrozdek commented on src/content/learn/rendering-lists.md
> +Chcąc uzyskać tylko te elementy, gdzie `profession` jest ustawione na `'chemik'`, odpowiednia funkcja "testu" powinna wyglądać tak: `(person) => person.profession === 'chemik'`. Oto sposób jak to wsz
```suggestion
Chcąc uzyskać tylko te elementy, gdzie `profession` jest ustawione na `'chemik'`, odpowiednia funkcja "testu" powinna wyglądać tak: `(person) => person.profession === 'chemik'`. Oto sposób na to, jak to wszystko połączyć w całość:
```

2024-02-26 00:33 UTC, jakubdrozdek commented on src/content/learn/rendering-lists.md
> +Funkcje strzałkowe (ang. _arrow function_) niejawnie zwracają wyrażenie znajdujące się zaraz po `=>`, więc nie musisz użyć instrukcji `return`:
```suggestion
Funkcje strzałkowe (ang. _arrow function_) niejawnie zwracają wyrażenie znajdujące się zaraz po `=>`, więc nie musisz używać instrukcji `return`:
```

2024-02-26 00:33 UTC, jakubdrozdek commented on src/content/learn/rendering-lists.md
> +* **Klucze muszą być unikalne między rodzeństwem.** Jednakże, używanie tych samych kluczy dla węzłów JSX w _różnych_ tablicach jest jak najbardziej w porządku.
```suggestion
* **Klucze muszą być unikalne między rodzeństwem.** Jednakże używanie tych samych kluczy dla węzłów JSX w _różnych_ tablicach jest jak najbardziej w porządku.
```

2024-02-26 00:33 UTC, jakubdrozdek commented on src/content/learn/rendering-lists.md
> +Użyta tutaj składnia `<Recipe {...recipe} key={recipe.id} />` to skrócony zapis mówiący "przekaż wszystkie właściwości obiektu `recipe` jako właściwości do komponentu `Recipe`". Możesz także przekaza
```suggestion
Użyta tutaj składnia `<Recipe {...recipe} key={recipe.id} />` to skrócony zapis, mówiący "przekaż wszystkie właściwości obiektu `recipe` jako właściwości do komponentu `Recipe`". Możesz także przekazać każdą właściwość jawnie: `<Recipe id={recipe.id} name={recipe.name} ingredients={recipe.ingredients} key={recipe.id} />`.
```

2024-02-26 00:33 UTC, jakubdrozdek commented on src/content/learn/rendering-lists.md
> +W tym przykładzie renderowany jest znany haiku autorstwa Tachibana Hokushi, z każdą linią umieszczoną w tagu `<p>`. Twoim zadaniem jest wstawienie separatorem `<hr />` między każdym akapitem. Ostatec
```suggestion
W tym przykładzie renderowany jest znany haiku autorstwa Tachibana Hokushi, z każdą linią umieszczoną w tagu `<p>`. Twoim zadaniem jest wstawienie separatora `<hr />` między każdym akapitem. Ostateczna struktura powinna wyglądać tak:
```

2024-02-26 00:33 UTC, jakubdrozdek commented on src/content/learn/rendering-lists.md
> +Ewentualnie, możesz wyrenderować kolekcję fragmentów, które zawierają `<hr />` i `<p>...</p>`. Jednakże, skrócona składnia `<>...</>` nie wspiera przekazywania kluczy, więc musisz użyć składni `<Frag
```suggestion
Ewentualnie, możesz wyrenderować kolekcję fragmentów, które zawierają `<hr />` i `<p>...</p>`. Jednak skrócona składnia `<>...</>` nie wspiera przekazywania kluczy, więc musisz użyć składni `<Fragment>`:
```

2024-03-23 21:01 UTC, dawidowski commented
I have messed up git history and can't recover from it ☹️
I will try to present my changes (including fixes from reviewers) in new PR with new branch.

2024-03-24 08:50 UTC, closed without merging