Final translation
reactjs/pl.reactjs.org pull request #491
Opened 2024-10-27 09:14 UTC by wizarddos

2024-11-09 17:59 UTC, dawidsabat commented
@wizarddos, skończyłem review, ogólnie super, że się tego podjąłeś, ale mam kilka uwag. Są pewne błędu początkującego, które na pewno poprawisz 😉 
- Jest trochę literówek. Większość z nich może być łatwo wykryta i poprawiona z pomocą jakiś wtyczek do IDE.
- Czasami brakuje kropek, szczególnie w ostatnich zdaniach akapitów lub gdy zdanie kończy się linkiem.
- Momentami brakuje konsekwencji w tłumaczeniu danego terminu, musisz to lepiej pilnować 😉
- Jeśli nie jesteś pewien jak dany termin tłumaczyć, przeszukaj kod i zobacz jakaś z opcji jest już używana i staraj się nią podążać.
- Zwracaj uwagę na przecinki. Język angielski ma inne zasady ich dotyczące.

2024-11-09 20:27 UTC, wizarddos commented
Jasne, dzięki wielkie za review. 

Prawda że to pewnie takie błędy, bo co jak co ale to pierwszy tekst który tłumaczę. Jeszcze raz dzięki i niedługo wrzucę odpowiedni fix

2024-12-08 10:05 UTC, dawidsabat commented
@wizarddos, planujesz wprowadzić poprawki jakoś niebawem? Szkoda żeby Twoja praca poszła na marne, jest blisko do mety 😉

2024-12-09 10:00 UTC, wizarddos commented
Oczywiście że planuję, miałem po prostu ostatnio sporo roboty. Jak znajdę chwilę to na pewno wszystko poprawię

2025-03-26 20:56 UTC, dawidsabat requested changes

2025-03-26 20:56 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Często zauważysz `onClick={handleClick}`, `onMouseEnter={handleMouseEnter}` itp.
Tu chyba uciekł Ci kawałek tekstu do przetłumaczenia. Zbyt skrótowo to wygląda.
```suggestion
Zgodnie z konwencją, nazwy funkcji obsługujących zdarzenia zazwyczaj zaczynają się od `handle`, po którym następuje nazwa zdarzenia. Często zobaczysz składnię taką jak `onClick={handleClick}`, `onMouseEnter={handleMouseEnter}` i podobne.
```

2025-03-26 21:03 UTC, dawidsabat commented
Hej @wizarddos, przepraszam, ale trochę nie ogarnąłem GitHuba i zapomniałem, że moje komentarze nie są widoczne dopóki nie zakończę review. W każdym razie sugestie są już dostępne, możesz je użyć. Przepraszam raz jeszcze 🥲

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +React pozwala nam dodać *procedury obsługi zdarzeń* (ang. _event handlers_) do naszego JSXa. Procedury obsługi zdarzeń to twoje własne funkcje, które zostaną wywołane w odpowiedzi na interakcje tj. k
```suggestion
React pozwala nam dodać *procedury obsługi zdarzeń* (ang. _event handlers_) do naszego JSX-a. Procedury obsługi zdarzeń to twoje własne funkcje, które zostaną wywołane w odpowiedzi na interakcje takie jak klikanie, najeżdżanie kursorem, zaznaczanie pól tekstowych itp.
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +3. Dodaj `onClick={handleClick}` do JSXa `<button>`.
```suggestion
3. Dodaj `onClick={handleClick}` do JSX-a `<button>`.
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +1. Zadeklaruj funkcję `handleClick` *wewnątrz* twojego komponentu `Button`.
```suggestion
1. Zadeklaruj funkcję `handleClick` *wewnątrz* swojego komponentu `Button`.
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +   * Wywołuje `e.stopPropagation()`, powstrzymując obiekt przed przekazaniem dalej.
```suggestion
   * Wywołuje `e.stopPropagation()`, powstrzymując zdarzenie przed przekazaniem dalej.
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Przechwytywanie zdarzeń przydaje się przy tworzeniu np. routerów czy analityki, ale prawdopodobnie nie znajdzie dla niego szerszego zastosowania w kodzie aplikacji.
```suggestion
Przechwytywanie zdarzeń przydaje się przy tworzeniu np. routerów czy analityki, ale prawdopodobnie nie znajdziesz dla tego szerszego zastosowania w kodzie aplikacji.
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Jeśli używając propagacji jest ci ciężko wyśledzić, które procedury są wykonywane i dlaczego, spróbuj tego podejścia.
```suggestion
Jeśli używając propagacji jest ci ciężko prześledzić, które procedury są wykonywane i dlaczego, spróbuj tego podejścia.
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +W przeciwieństwie do funkcji renderujących, procedury obsługi zdarzeń nie muszą być [czyste](/learn/keeping-components-pure), więc jest to świetne miejsce by coś *zmienić* - na przykład, wartość inpu
```suggestion
W przeciwieństwie do funkcji renderujących, procedury obsługi zdarzeń nie muszą być [czyste](/learn/keeping-components-pure), więc jest to świetne miejsce by coś *zmienić* - na przykład, wartość pola tekstowego w odpowiedzi na wpisywanie lub listę po naciśnięciu przycisku. Jednakże, aby cokolwiek pozmieniać, musisz wpierw jakoś to przechować. W Reakcie używa się do tego [stanu, czyli pamięci komponentu](/learn/state-a-components-memory). Wszystkiego o tym nauczysz się na następnej stronie.
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Problemem jest to, że `<button onClick={handleClick()}>` _wywołuje_ funkcję `handleClick` zamiast ją _przekazywać_ podczas renderowania. Usunięcie `()`, aby przycisk został w formie `<button onClick=
```suggestion
Problem polega na tym, że `<button onClick={handleClick()}>` _wywołuje_ funkcję `handleClick` zamiast ją _przekazywać_ podczas renderowania. Usunięcie `()`, aby przycisk został w formie `<button onClick={handleClick}>` naprawi błąd:
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +W drugim przykładzie `()` na końcu `handleClick()` *natychmiast* wykonuje funkcję podczas [renderowania](/learn/render-and-commit), bez żadnych kliknięć. Dzieje się tak, ponieważ JavaScript wewnątrz
```suggestion
W drugim przykładzie `()` na końcu `handleClick()` *natychmiast* wykonuje funkcję podczas [renderowania](/learn/render-and-commit), bez żadnych kliknięć. Dzieje się tak, ponieważ JavaScript wewnątrz [JSX-owych nawiasów `{` i `}`](/learn/javascript-in-jsx-with-curly-braces) wykonuje się od razu.
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Zwróć uwagę na to, że komponent `App` nie musi wiedzień *co* `Toolbar` zrobi z `onPlayMovie` lub `onUploadImage`. To szczegół w implementacji `Toolbar`. Tutaj, `Toolbar` przekazuje je niżej jako proc
```suggestion
Zwróć uwagę na to, że komponent `App` nie musi wiedzieć *co* `Toolbar` zrobi z `onPlayMovie` lub `onUploadImage`. To szczegół w implementacji `Toolbar`. Tutaj, `Toolbar` przekazuje je niżej jako procedury `onClick` do swoich komponentów `Button`, ale później mogą również zostać wywołane skrótem klawiszowym. Nazywanie właściwości po interakcjach specyficznych dla aplikacji np. `onPlayMovie` pozwala ci wygodnie zmieniać, w jaki sposób będą później użyte.
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Ewentualnie, możesz owinąć wywołanie funkcji w inną funkcję w taki sposób `<button onClick={() => handleClick()}>`:
```suggestion
Ewentualnie, możesz opakować wywołanie funkcji w inną funkcję w taki sposób `<button onClick={() => handleClick()}>`:
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +| przekazanie funkcji (correct)           | wywołanie funkcji (nieprawidłowo) |
```suggestion
| przekazanie funkcji (prawidłowo)        | wywołanie funkcji (nieprawidłowo) |
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Aby dodać procedurę obsługi zdarzeń, najpierw zdefiniuj funkcję, a następnie [przekaż ją jako właściwość (ang. _prop_)](/learn/passing-props-to-a-component) do odpowiedniego tagu JSX. Na przykład, ot
```suggestion
Aby dodać procedurę obsługi zdarzeń, najpierw zdefiniuj funkcję, a następnie [przekaż ją jako właściwość (ang. _prop_)](/learn/passing-props-to-a-component) do odpowiedniego elementu JSX. Na przykład, oto przycisk, który jeszcze nic nie robi:
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Możesz sprawić, aby pokazywał wiadomość po kliknięciu go przez użytkownika w tych trzech krokach:
```suggestion
Możesz sprawić, by po kliknięciu przez użytkownika przycisk pokazywał wiadomość, wykonując trzy kroki:
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Zdefiniowana funkcja `handleClick`, która jest potem [przekazana jako właściwość](/learn/passing-props-to-a-component) do `<button>`, jest **procedurą obsługi zdarzeń.** Funkcje taka jak ta:
```suggestion
Zdefiniowana funkcja `handleClick`, która jest potem [przekazana jako właściwość](/learn/passing-props-to-a-component) do `<button>`, jest **procedurą obsługi zdarzeń.** Funkcje takie jak ta:
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Oprócz tego, możesz zdefiniować procedurę obsługi zdarzeń w miejscu wywołania w JSX:
```suggestion
Możesz też zdefiniować procedurę obsługi zdarzeń w miejscu wywołania w JSX:
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Oba style dadzą ten sam rezultat. Ten sposób definiowania jest wygodny dla krótkich funkcji.
```suggestion
Wszystkie te sposoby dadzą ten sam rezultat. Ten sposób definiowania jest wygodny dla krótkich funkcji.
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Przekazywanie kodu w lini, tak jak w poniższym przykładzie, nie uruchomi się na kliknięcie - wywoła się za każdym razem, gdy komponent się wyrenderuje:
```suggestion
Przekazywanie kodu w linii, tak jak w poniższym przykładzie, nie uruchomi się na kliknięcie - wywoła się za każdym razem, gdy komponent się wyrenderuje:
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Ponieważ procedury są deklarowane wewnątrz komponentu, mają dostęp do jego właściwości. Oto przycisk, który po kliknięciu pokaże alert z właściwością `message`:
```suggestion
Ponieważ procedury obsługi zdarzeń są deklarowane wewnątrz komponentu, mają dostęp do jego właściwości. Oto przycisk, który po kliknięciu pokaże alert z właściwością `message`:
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Często będziesz chcieć, aby komponent-rodzic zdefiniował dziecku procedurę obsługi zdarzeń. Przyjrzyj się przyciskom: w zależności od tego, gdzie użyjesz komponentu `Button`, możesz chcieć wykonać in
```suggestion
Często będziesz chcieć, aby komponent nadrzędny zdefiniował dziecku procedurę obsługi zdarzeń. Przyjrzyj się przyciskom: w zależności od tego, gdzie użyjesz komponentu `Button`, możesz chcieć wykonać inną funkcję - być może jeden odtwarza film, a drugi dodaje obrazek?
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Jeśli używasz [systemów projektu](https://uxdesign.cc/everything-you-need-to-know-about-design-systems-54b109851969), często komponenty, takie jak przyciski, posiadają style, ale nie definiują zachow
```suggestion
Jeśli używasz [systemu projektowania (ang. _design system_)](https://uxdesign.cc/everything-you-need-to-know-about-design-systems-54b109851969), często komponenty, takie jak przyciski, posiadają style, ale nie definiują zachowania. Zamiast tego, komponenty typu `PlayButton` czy `UploadButton` będą przekazywały w dół procedury obsługi zdarzeń.
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Komponenty wbudowane tj. `<button>` i `<div>` wspierają jedynie [nazwy zdarzeń przeglądarki](/reference/react-dom/components/common#common-props) jak `onClick`. Jednak, gdy budujesz własne komponenty
```suggestion
Komponenty wbudowane, takie jak `<button>` i `<div>` wspierają jedynie [nazwy zdarzeń przeglądarki](/reference/react-dom/components/common#common-props) jak `onClick`. Jednak, gdy budujesz własne komponenty, możesz nazywać ich właściwości procedur obsługi jakkolwiek chcesz.
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Według konwencji, właściwości procedur obsługi zdarzeń  powinny zaczynać się od `on` i dużej litery tuż za nim.
```suggestion
Według konwencji, właściwości procedur obsługi zdarzeń  powinny zaczynać się od `on` i dużej litery tuż po nim.
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +W tym przykładzie `<button onClick={onSmash}>` pokazuje, że przeglądarkowy `<button>` (lowercase) nadal potrzebuje właściwości `onClick`, ale jej nazwa otrzymana przez twój własny komponent `Button`
```suggestion
W tym przykładzie `<button onClick={onSmash}>` pokazuje, że przeglądarkowy `<button>` (lowercase) nadal potrzebuje właściwości `onClick`, ale jej nazwa otrzymana przez twój własny komponent `Button` może być jaka chcesz!
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Gdy twój komponent wspiera wiele interakcji, możesz nazwać właściwości procedur obsługi zdarzeń zgodnie z pojęciami typowymi dla twojej aplikacji. Na przykład, ten komponent `Toolbar` otrzymuje proce
```suggestion
Gdy twój komponent wspiera wiele różnych interakcji, możesz nazwać właściwości procedur obsługi zdarzeń zgodnie z pojęciami typowymi dla twojej aplikacji. Na przykład, ten komponent `Toolbar` otrzymuje procedury `onPlayMovie` i `onUploadImage`:
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Procedury obsługi zdarzeń wyłapią również zdarzenia z któregokolwiek komponentu potomnego. Mówimy wtedy, że zdarzenie "bąbelkuje" (ang. _bubbles_) lub "propaguje" (ang. _propagates_) w górę drzewa: z
```suggestion
Procedury obsługi zdarzeń wyłapią również zdarzenia pochodzące z dowolnego komponentu potomnego. Mówimy wtedy, że zdarzenie "bąbelkuje" (ang. _bubbles_) lub "propaguje" (ang. _propagates_) w górę drzewa: zaczyna się to tam, gdzie zdarzenie miało miejsce, a potem idzie w górę.
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Ten `<div>` zawiera dwa przyciski. Oba elementy `<div>` i każdy przycisk mają swoją własną obsługę `onClick`. Jak myślisz, która z nich zostanie uruchomiona, gdy naciśniesz przycisk?
```suggestion
Ten `<div>` zawiera dwa przyciski. Zarówno element `<div>`, jak i każdy z przycisków mają swoją własną obsługę `onClick`. Jak myślisz, która z nich zostanie uruchomiona, gdy naciśniesz przycisk?
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Naciskając na którykolwiek z przycisków, ich `onClick` uruchomi się jako pierwszy. Następnie wykona się `onClick` z nadrzędnego `<div>`a, zatem pojawią się 2 wiadomości. Jeśli naciśniesz stricte na p
```suggestion
Naciskając na którykolwiek z przycisków, `onClick` przypisany do nich uruchomi się jako pierwszy. Następnie wykona się `onClick` z nadrzędnego elementu `<div>`, zatem pojawią się dwie wiadomości. Jeśli naciśniesz wprost na pasek, jedynie `onClick` elementu `<div>` zostanie uruchomiony.
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Procedury obsługi zdarzeń otrzymują jako jedyny argument **obiekt zdarzenia** (ang. _event object_). Zwyczajowo nazywany jest `e`, co pochodzi od angielskiego "event". Możesz go użyć do odczytu infor
```suggestion
Procedury obsługi zdarzeń otrzymują jako jedyny argument **obiekt zdarzenia** (ang. _event object_). Zwyczajowo nazywany jest `e`, co pochodzi od angielskiego "event". Możesz go użyć do odczytu informacji o zdarzeniu.
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +      <h2>Kliknięć na stronie: {clicks}</h2>
```suggestion
      <h2>Liczba kliknięć na stronie: {clicks}</h2>
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +      <h2>Kliknięć na stronie: {clicks}</h2>
```suggestion
      <h2>Liczba kliknięć na stronie: {clicks}</h2>
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +#### Podpinanie zdarzeń {/*wire-up-the-events*/}
```suggestion
#### Podłączanie zdarzeń {/*wire-up-the-events*/}
```

2025-06-19 13:07 UTC, dawidsabat commented on src/content/learn/responding-to-events.md
> +Niektóre zdarzenia przeglądarki mają domyślne zachowanie powiązane z nim. Na przykład zdarzenie wysłania formularza, które następuje, gdy naciśnięty zostanie przycisk w jego wnętrzu, domyślnie przeła
```suggestion
Niektóre zdarzenia przeglądarki mają domyślne zachowanie powiązane z nimi. Na przykład zdarzenie wysłania formularza, które następuje, gdy naciśnięty zostanie przycisk w jego wnętrzu, domyślnie przeładuje całą stronę:
```

2025-06-19 13:29 UTC, dawidsabat approved these changes

2025-06-19 13:37 UTC, merged